package view;

//import MyCustom.XuLyFileExcel;
import MyCustom.MyDialog;
import MyCustom.MyFileChooser;
import MyCustom.XuLyFileExcel;
import bus.SanPhamBUS;
import dao.SanPhamDAO;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.SanPhamModel;

/**
 *
 * @author HungPhanPC
 */
public class QLSPJFrame extends javax.swing.JFrame {
    
    SanPhamBUS spBUS = new SanPhamBUS();
    DefaultTableModel dtmSanPham;
    ArrayList<SanPhamModel> lstSP;
    String ten = "";

    /**
     * Creates new form QLSPJFrame
     */
    public QLSPJFrame() throws Exception {
        initComponents();
        LoadSPTable();
        lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));
        fmfMaSP.setEnabled(false);
        setExtendedState(QLSPJFrame.MAXIMIZED_BOTH);
        setTitle("Phần mềm bán Pizza mang về");
          ImageIcon image = new ImageIcon("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\Icon\\sanpham-pizza.png");
        setIconImage(image.getImage());

    }

    DecimalFormat dcf = new DecimalFormat("###,###");

    public void LoadSPTable() throws Exception {
        DefaultTableModel dtmSanPham = new DefaultTableModel();
        dtmSanPham.setColumnIdentifiers(new Object[]{"Mã SP", "Tên SP", "Mã loại", "Đơn giá", "Còn lại", "Đơn vị tính", "Ảnh"});
        tblSanPham.setModel(dtmSanPham);
        dtmSanPham.setRowCount(0);
        ArrayList<SanPhamModel> dssp = null;
        dssp = spBUS.getListSanPham();

        for (SanPhamModel sp : SanPhamDAO.TimSanPhamTheoTen(ten)) {
            Vector vec = new Vector();
            vec.add(sp.getMasp());
            vec.add(sp.getTensp());
            vec.add(sp.getMaloai());
            vec.add(dcf.format(sp.getDongia()));
            vec.add(dcf.format(sp.getSoluong()));
            vec.add(sp.getDonvitinh());
            vec.add(sp.getHinhanh());
            dtmSanPham.addRow(vec);
        }

    }

    private void xuLyChonAnh() {
        JFileChooser fileChooser = new MyFileChooser("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Tệp hình ảnh", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileAnhSP = fileChooser.getSelectedFile();
            lblAnhSP.setIcon(getAnhSP(fileAnhSP.getPath()));
        }
    }

    //Hàm hiển thị ảnh
    File fileAnhSP;

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File image = new File(src);

        if (!image.exists()) {
            src = "default.png";
            image = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham" + src);
        }

        try {
            img = ImageIO.read(image);
            fileAnhSP = new File(src);
        } catch (IOException e) {
            fileAnhSP = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);
        }

        return null;
    }

    private void loadAnh(String anh) {
        lblAnhSP.setIcon(getAnhSP(anh));
    }

    private void luuFileAnh() {
        BufferedImage bImage = null;
        try {
            File initialImage = new File(fileAnhSP.getPath());
            bImage = ImageIO.read(initialImage);

            ImageIO.write(bImage, "png", new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\" + fileAnhSP.getName()));

        } catch (IOException e) {
            System.out.println("Exception occured :" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fmfMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fmfDonGia = new javax.swing.JFormattedTextField();
        fmfSoLuong = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbMaLoai = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblAnhSP = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 900));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledSelectedBackground"));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã sản phẩm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel5, gridBagConstraints);

        fmfMaSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(fmfMaSP, gridBagConstraints);

        txtTenSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(txtTenSP, gridBagConstraints);

        txtDVT.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(txtDVT, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tên sản phẩm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mã loại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Đơn giá:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel8, gridBagConstraints);

        fmfDonGia.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(fmfDonGia, gridBagConstraints);

        fmfSoLuong.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel10.add(fmfSoLuong, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("THÔNG TIN SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(24, 20, 17, 20);
        jPanel10.add(jLabel9, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Đơn vị tính:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Số lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel10.add(jLabel18, gridBagConstraints);

        cbMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMaLoai.setMaximumRowCount(50);
        cbMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbMaLoai.setPreferredSize(new java.awt.Dimension(210, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel10.add(cbMaLoai, gridBagConstraints);

        jPanel4.add(jPanel10, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(27, 0, 27, 0);
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));
        jPanel9.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập từ khóa để tìm kiếm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 17, 16, 17);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtTimKiem.setColumns(20);
        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(16, 17, 16, 17);
        jPanel1.add(txtTimKiem, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/choose-image-icon.png"))); // NOI18N
        jButton1.setText("Chọn ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(35, 17, 16, 17);
        jPanel1.add(jButton1, gridBagConstraints);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(lblAnhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel9.add(jPanel1, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(36, 0, 27, 0);
        jPanel3.add(jPanel9, gridBagConstraints);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/Refresh-icon.png"))); // NOI18N
        jButton8.setText("Đặt lại");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton8, gridBagConstraints);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/fix-icon.png"))); // NOI18N
        jButton9.setText("Sửa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton9, gridBagConstraints);

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/add-icon.png"))); // NOI18N
        jButton10.setText("Thêm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton10, gridBagConstraints);

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/delete-icon.png"))); // NOI18N
        jButton11.setText("Xóa");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton11, gridBagConstraints);

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/excel-icon.png"))); // NOI18N
        jButton12.setText("Xuất Excel");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton12, gridBagConstraints);

        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\Icon\\excel-icon.png")); // NOI18N
        jButton13.setText("Nhập Excel");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel3.add(jButton13, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUẢN LÍ SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel3.add(jLabel4, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        fmfMaSP.setEnabled(false);
        int row = tblSanPham.getSelectedRow();
        String anh = tblSanPham.getValueAt(row, 6) + "";
        if (row >= 0) {

            fmfMaSP.setText(tblSanPham.getValueAt(row, 0).toString());
            txtTenSP.setText(tblSanPham.getValueAt(row, 1).toString());
            cbMaLoai.setSelectedItem(tblSanPham.getValueAt(row, 2).toString());
            fmfDonGia.setText(tblSanPham.getValueAt(row, 3).toString());
            fmfSoLuong.setText(tblSanPham.getValueAt(row, 4).toString());
            txtDVT.setText(tblSanPham.getValueAt(row, 5).toString());

            loadAnh("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\" + anh);
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            // TODO add your handling code here:
            xuLyThemSanPham();
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        xuLyChonAnh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        xuLyCapNhat();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            // TODO add your handling code here:
            xuLyXoaSanPham();
            xuLyCapNhat();
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            xuLySuaSanPham();
            xuLyCapNhat();
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        xuLyNhapExcel();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        xuLyXuatExcel();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        ten = txtTimKiem.getText();
        try {
            LoadSPTable();
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyPressed
    private void xuLyXuatExcel() {
        XuLyFileExcel xuatFile = new XuLyFileExcel();
        xuatFile.xuatExcel(tblSanPham);
    }

    private void xuLyNhapExcel() {
        MyDialog dlg = new MyDialog("Dữ liệu cũ sẽ bị xoá, tiếp tục?", MyDialog.WARNING_DIALOG);
        if (dlg.getAction() != MyDialog.OK_OPTION) {
            return;
        }

        XuLyFileExcel nhapFile = new XuLyFileExcel();
        nhapFile.nhapExcel(tblSanPham);

        int row = tblSanPham.getRowCount();
        for (int i = 0; i < row; i++) {
            String masp = tblSanPham.getValueAt(i, 1) + "";
            String ten = tblSanPham.getValueAt(i, 2) + "";
            String loai = tblSanPham.getValueAt(i, 3) + "";
            String donGia = tblSanPham.getValueAt(i, 4) + "";
            String soLuong = tblSanPham.getValueAt(i, 5) + "";
            String donViTinh = tblSanPham.getValueAt(i, 6) + "";
            String anh = tblSanPham.getValueAt(i, 7) + "";

            spBUS.nhapSanPhamTuExcel(masp, ten, loai, soLuong, donViTinh, anh, donGia);
        }
    }

    private void xuLyThemSanPham() throws SQLException, Exception {

        String anh = fileAnhSP.getName();
        System.out.println(fileAnhSP.getName());
        boolean flag = spBUS.themSanPham(fmfMaSP.getText(), txtTenSP.getText(),
                cbMaLoai.getSelectedItem() + "",
                fmfSoLuong.getText(),
                txtDVT.getText(),
                anh, fmfDonGia.getText());
        spBUS.docListSanPham();
        LoadSPTable();
        luuFileAnh();

    }

    private void xuLyCapNhat() {
        try {
            fmfMaSP.setEnabled(true);
            LoadSPTable();
            fmfMaSP.setText("");
            cbMaLoai.setSelectedItem("1");
            txtTenSP.setText("");
            fmfSoLuong.setText("");
            txtDVT.setText("");
            fmfDonGia.setText("");
            lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void xuLySuaSanPham() throws Exception {
    try {
        String anh = fileAnhSP.getName();
        String masp = fmfMaSP.getText();
        int maLoai = Integer.parseInt(cbMaLoai.getSelectedItem().toString());
        int soLuongSP = Integer.parseInt(fmfSoLuong.getText());
        String tenSP = txtTenSP.getText();
        String dVT = txtDVT.getText();
        float donGiaSP = Float.parseFloat(fmfDonGia.getText().replace(",", ""));
        if (masp.equals("")) {
            new MyDialog("Chưa chọn sản phẩm để xóa!!", MyDialog.ERROR_DIALOG);
        } else {
            SanPhamModel sp = new SanPhamModel();

            int maSP = Integer.parseInt(masp);
            sp.setMasp(maSP);
            sp.setTensp(tenSP);
            sp.setMaloai(maLoai);
            sp.setSoluong(soLuongSP);
            sp.setDonvitinh(dVT);
            sp.setHinhanh(anh);
            sp.setDongia(donGiaSP);
            SanPhamDAO spdao = new SanPhamDAO();
            if (spdao.suaSanPham(sp)) {
                new MyDialog("Sửa thành công!", MyDialog.SUCCESS_DIALOG);
                LoadSPTable();
                luuFileAnh();
            } else {
                new MyDialog("Sửa thất bại!", MyDialog.ERROR_DIALOG);
            }
        }
    } catch (NumberFormatException ex) {
        new MyDialog("Chưa chọn sản phẩm để sửa!", MyDialog.ERROR_DIALOG);
    }
}


    private void xuLyXoaSanPham() throws Exception {
        String masp = fmfMaSP.getText();
        if (masp.equals("")) {
            new MyDialog("Chưa chọn sản phẩm để xóa!!", MyDialog.ERROR_DIALOG);
        } else {
            MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn xoá?", MyDialog.WARNING_DIALOG);
            if (dlg.OK_OPTION == dlg.getAction()) {
                boolean flag = spBUS.xoaSanPham(fmfMaSP.getText());
                if (flag) {
                    LoadSPTable();
                }
            }
        }
        LoadSPTable();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLSPJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMaLoai;
    private javax.swing.JFormattedTextField fmfDonGia;
    private javax.swing.JTextField fmfMaSP;
    private javax.swing.JFormattedTextField fmfSoLuong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
