/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import MyCustom.MyDialog;
import MyCustom.MyFileChooser;
import bus.SanPhamBUS;
import dao.SanPhamDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.SanPhamModel;

/**
 *
 * @author HungPhanPC
 */
public class ThemSPJFrame extends javax.swing.JFrame {

    SanPhamBUS spBUS = new SanPhamBUS();
    DefaultTableModel dtmSanPham;
    ArrayList<SanPhamModel> lstSP;
    DecimalFormat dcf = new DecimalFormat("###,###");

    /**
     * Creates new form ThemSPJFrame
     */
    public ThemSPJFrame() throws Exception {
        initComponents();
        lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));
        LoadSPTable();
        setTitle("Phần mềm bán Pizza mang về");
          ImageIcon image = new ImageIcon("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\Icon\\sanpham-pizza.png");
        setIconImage(image.getImage());
    }

    public void LoadSPTable() throws Exception {
        DefaultTableModel dtmSanPham = new DefaultTableModel();
        dtmSanPham.setColumnIdentifiers(new Object[]{"Mã SP", "Tên SP", "Mã loại", "Đơn giá", "Còn lại", "Đơn vị tính", "Ảnh"});
        tblSanPham.setModel(dtmSanPham);
        dtmSanPham.setRowCount(0);
        ArrayList<SanPhamModel> dssp = null;
        dssp = spBUS.getListSanPham();

        for (SanPhamModel sp : SanPhamDAO.getALL()) {
            Vector vec = new Vector();
            vec.add(sp.getMasp());
            vec.add(sp.getTensp());
            vec.add(sp.getMaloai());
            vec.add(dcf.format(sp.getDongia()));
            vec.add(dcf.format(sp.getSoluong()));
            vec.add(sp.getDonvitinh());
            vec.add(sp.getHinhanh());
            dtmSanPham.addRow(vec);
        }
    }

    private void xuLyChonAnh() {
        JFileChooser fileChooser = new MyFileChooser("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Tệp hình ảnh", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileAnhSP = fileChooser.getSelectedFile();
            lblAnhSP.setIcon(getAnhSP(fileAnhSP.getPath()));
        }
    }

    //Hàm hiển thị ảnh
    File fileAnhSP;

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File image = new File(src);

        if (!image.exists()) {
            src = "default.png";
            image = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham" + src);
        }

        try {
            img = ImageIO.read(image);
            fileAnhSP = new File(src);
        } catch (IOException e) {
            fileAnhSP = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);
        }

        return null;
    }

    private void loadAnh(String anh) {
        lblAnhSP.setIcon(getAnhSP(anh));
    }

    private void luuFileAnh() {
        BufferedImage bImage = null;
        try {
            File initialImage = new File(fileAnhSP.getPath());
            bImage = ImageIO.read(initialImage);

            ImageIO.write(bImage, "png", new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\" + fileAnhSP.getName()));

        } catch (IOException e) {
            System.out.println("Exception occured :" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblAnhSP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fmfMaSP = new javax.swing.JFormattedTextField();
        fmfDonGia = new javax.swing.JFormattedTextField();
        fmfSoLuong = new javax.swing.JFormattedTextField();
        txtDVT = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        cbMaLoai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(lblAnhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(19, 3, 12, 3);
        jPanel5.add(jPanel6, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ảnh sản phẩm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 3);
        jPanel5.add(jLabel3, gridBagConstraints);

        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/choose-image-icon.png"))); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 17, 3);
        jPanel5.add(btnChonAnh, gridBagConstraints);

        jPanel2.add(jPanel5, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 18, 39);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THÔNG TIN SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã sản phẩm :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên sản phẩm :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã loại :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số lượng :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Đơn vị tính :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Đơn giá :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(jLabel9, gridBagConstraints);

        fmfMaSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(fmfMaSP, gridBagConstraints);

        fmfDonGia.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(fmfDonGia, gridBagConstraints);

        fmfSoLuong.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(fmfSoLuong, gridBagConstraints);

        txtDVT.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(txtDVT, gridBagConstraints);

        txtTenSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(txtTenSP, gridBagConstraints);

        cbMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbMaLoai.setPreferredSize(new java.awt.Dimension(210, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 27);
        jPanel4.add(cbMaLoai, gridBagConstraints);

        jPanel3.add(jPanel4, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 18, 39);
        jPanel1.add(jPanel3, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÊM SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 18, 18);
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 102, 0));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel8.add(btnThem, gridBagConstraints);

        btnDatLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDatLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/Refresh-icon.png"))); // NOI18N
        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel8.add(btnDatLai, gridBagConstraints);

        jPanel7.add(jPanel8, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jPanel7, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        fmfMaSP.setEnabled(false);
        int row = tblSanPham.getSelectedRow();
        String anh = tblSanPham.getValueAt(row, 6) + "";
        if (row >= 0) {

            fmfMaSP.setText(tblSanPham.getValueAt(row, 0).toString());
            txtTenSP.setText(tblSanPham.getValueAt(row, 1).toString());
            cbMaLoai.setSelectedItem(tblSanPham.getValueAt(row, 2).toString());
            fmfDonGia.setText(tblSanPham.getValueAt(row, 3).toString());
            fmfSoLuong.setText(tblSanPham.getValueAt(row, 4).toString());
            txtDVT.setText(tblSanPham.getValueAt(row, 5).toString());
            loadAnh("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\" + anh);
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked
    private void xuLyThemSanPham() throws SQLException, Exception {
        try {
            
        String anh = fileAnhSP.getName();
        System.out.println(fileAnhSP.getName());
        boolean flag = spBUS.themSanPham(fmfMaSP.getText(), txtTenSP.getText(),
                cbMaLoai.getSelectedItem() + "",
                fmfSoLuong.getText(),
                txtDVT.getText(),
                anh, fmfDonGia.getText());
        spBUS.docListSanPham();
        LoadSPTable();
        luuFileAnh();
        } catch (Exception e) {
            new MyDialog("Mã sản phẩm trùng!!! Vui lòng nhập lại mã sản phẩm!!!",MyDialog.ERROR_DIALOG);
        }

    }
    private void xuLyCapNhat() {
        try {
            fmfMaSP.setEnabled(true);
            LoadSPTable();
            fmfMaSP.setText("");
            cbMaLoai.setSelectedItem("1");
            txtTenSP.setText("");
            fmfSoLuong.setText("");
            txtDVT.setText("");
            fmfDonGia.setText("");
            lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));
        } catch (Exception ex) {
            Logger.getLogger(QLSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        xuLyChonAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            xuLyThemSanPham();
            xuLyCapNhat();
        } catch (Exception ex) {
            Logger.getLogger(ThemSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:
        xuLyCapNhat();
    }//GEN-LAST:event_btnDatLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ThemSPJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ThemSPJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbMaLoai;
    private javax.swing.JFormattedTextField fmfDonGia;
    private javax.swing.JFormattedTextField fmfMaSP;
    private javax.swing.JFormattedTextField fmfSoLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
