/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bus.ThongKeBUS;
import dao.ThongKeDAO;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author HungPhanPC
 */
public class ThongKeJFrame extends javax.swing.JFrame {

    private DecimalFormat dcf = new DecimalFormat("###,###");

    /**
     * Creates new form ThongKeJFrame
     */
    public ThongKeJFrame() throws Exception {
        initComponents();
        JComboBox<Integer> cmbNam;
        cmbNam = new JComboBox<>();
        ThongKeDAO tkdao = new ThongKeDAO();
        setExtendedState(ThongKeJFrame.MAXIMIZED_BOTH);

        QuanLyThongKeController controller = new QuanLyThongKeController();
        ThongKeBUS thongKeBUS = new ThongKeBUS();
        controller.setDataToChart1(Chart1);
        controller.setDataToChart2(Chart2);
        // Thống kê
        lblThongKeThucDon.setText(dcf.format(tkdao.getTongSoLuongSP()));
        lblThongKeDoanhThu.setText(dcf.format(tkdao.getDoanhThu()));
        lblThongKeKH.setText(dcf.format(tkdao.getSoLuongKhachHang()));
        lblThongKeNV.setText(dcf.format(tkdao.getSoLuongNhanVien()));
        setTitle("Phần mềm bán Pizza mang về");
          ImageIcon image = new ImageIcon("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\Icon\\sanpham-pizza.png");
        setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Chart1 = new javax.swing.JPanel();
        Chart2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblThongKeThucDon = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblThongKeDoanhThu = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblThongKeKH = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblThongKeNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 102, 0));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THỐNG KÊ CỬA HÀNG BÁN PIZZA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(8, 17, 48, 17);
        jPanel8.add(jLabel2, gridBagConstraints);

        Chart1.setMinimumSize(new java.awt.Dimension(650, 500));
        Chart1.setPreferredSize(new java.awt.Dimension(700, 500));
        Chart1.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        jPanel8.add(Chart1, gridBagConstraints);

        Chart2.setMinimumSize(new java.awt.Dimension(650, 500));
        Chart2.setPreferredSize(new java.awt.Dimension(700, 500));
        Chart2.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 30);
        jPanel8.add(Chart2, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/icon-thongke-1.png"))); // NOI18N
        jLabel1.setText("Món trong thực đơn :");
        jPanel11.add(jLabel1);

        lblThongKeThucDon.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblThongKeThucDon.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeThucDon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblThongKeThucDon.setText(" 0");
        lblThongKeThucDon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(lblThongKeThucDon);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 100, 9, 26);
        jPanel8.add(jPanel11, gridBagConstraints);

        jPanel12.setBackground(new java.awt.Color(255, 102, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/icon-thongke-2.png"))); // NOI18N
        jLabel3.setText("Tổng doanh thu :");
        jPanel12.add(jLabel3);

        lblThongKeDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblThongKeDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeDoanhThu.setText("0");
        jPanel12.add(lblThongKeDoanhThu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 80, 9, 9);
        jPanel8.add(jPanel12, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(255, 102, 0));
        jPanel13.setMinimumSize(new java.awt.Dimension(220, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/icon-thongke-3.png"))); // NOI18N
        jLabel4.setText("Khách hàng :");
        jLabel4.setPreferredSize(new java.awt.Dimension(156, 32));
        jPanel13.add(jLabel4);

        lblThongKeKH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblThongKeKH.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeKH.setText("0");
        jPanel13.add(lblThongKeKH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 120, 9, 9);
        jPanel8.add(jPanel13, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(255, 102, 0));
        jPanel14.setMinimumSize(new java.awt.Dimension(200, 42));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/icon-thongke-4.png"))); // NOI18N
        jLabel5.setText("Nhân viên :");
        jPanel14.add(jLabel5);

        lblThongKeNV.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblThongKeNV.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeNV.setText("0");
        jPanel14.add(lblThongKeNV);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        jPanel8.add(jPanel14, gridBagConstraints);

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ThongKeJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ThongKeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Chart1;
    private javax.swing.JPanel Chart2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblThongKeDoanhThu;
    private javax.swing.JLabel lblThongKeKH;
    private javax.swing.JLabel lblThongKeNV;
    private javax.swing.JLabel lblThongKeThucDon;
    // End of variables declaration//GEN-END:variables
}
