/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;


import MyCustom.MyDialog;
import bus.SanPhamBUS;
import connect.Connect;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.SanPhamModel;
import view.QLSPJFrame;
import view.ThemSPJFrame;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.ChangePasswordJFrame;
import view.LoginJDialog;
import view.QLHDJFrame;
import view.QLKHJFrame;
import view.QLNVJFrame;
import view.ThongKeJFrame;


/**
 *
 * @author HungPhanPC
 */
public class MainJFrame extends javax.swing.JFrame {

    DefaultTableModel dtmGioHang = new DefaultTableModel();
    Double tonghoadon = 0.0;
    Double tongtatca = 0.0;
    Double bHeight = 0.0;
    ArrayList<String> itemName = new ArrayList<>();
    ArrayList<String> quantity = new ArrayList<>();
    ArrayList<String> itemPrice = new ArrayList<>();
    ArrayList<String> subtotal = new ArrayList<>();
    ArrayList<String> arrMaNV = new ArrayList<>();
    ArrayList<String> arrMaHD = new ArrayList<>();
    ArrayList<String> arrNgayLap = new ArrayList<>();
    ArrayList<String> arrTenNV = new ArrayList<>();
    SanPhamBUS spBUS = new SanPhamBUS();
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() throws Exception {
        initComponents();
        this.setSize(1400, 1000);
        this.setLocationRelativeTo(null);
        getSanPham();
        setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        cbLoaiSP.setEnabled(false);
        fmfDonGia.setEnabled(false);
        fmfMaSP.setEnabled(false);
        txtTenSP.setEnabled(false);
        txtHoTen.setEnabled(false);
        resetCTHD();
        ImageIcon image = new ImageIcon("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\Icon\\sanpham-pizza.png");
        setIconImage(image.getImage());
    }

    private void resetCTHD() {
        fmtMaHD.setEnabled(false);
        fmtMaKH.setEnabled(false);
        dsNgayTao.setEnabled(false);
        txtGhiChu.setEnabled(false);
    }

    public void phanQuyenNhanVien() {
        btnThemSP.setEnabled(false);
        btnThongKe.setEnabled(false);
        mnSanPham.setEnabled(false);
        mniThemSP.setEnabled(false);
        mniCNSP.setEnabled(false);
        mnNhanVien.setEnabled(false);
        mniPhanQuyen.setEnabled(false);
        mniThemNV.setEnabled(false);
        mniQLSP.setEnabled(false);
        mnHoaDon.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnThemSP = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fmfMaSP = new javax.swing.JFormattedTextField();
        fmfSoLuong = new javax.swing.JFormattedTextField();
        txtTenSP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fmfDonGia = new javax.swing.JFormattedTextField();
        cbLoaiSP = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtHoTen = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fmtMaNV = new javax.swing.JFormattedTextField();
        fmtMaHD = new javax.swing.JFormattedTextField();
        fmtMaKH = new javax.swing.JFormattedTextField();
        dsNgayTao = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblAnhSP = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnTrangChu = new javax.swing.JMenu();
        mnSanPham = new javax.swing.JMenu();
        mniThemSP = new javax.swing.JMenuItem();
        mniCNSP = new javax.swing.JMenuItem();
        mniXuatExcel = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniQLSP = new javax.swing.JMenuItem();
        mnHoaDon = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnKhachHang = new javax.swing.JMenu();
        mniThemKH = new javax.swing.JMenuItem();
        mniSuaKH = new javax.swing.JMenuItem();
        mniXoaKH = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniQLKH = new javax.swing.JMenuItem();
        mnNhanVien = new javax.swing.JMenu();
        mniThemNV = new javax.swing.JMenuItem();
        mniPhanQuyen = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniQLNV = new javax.swing.JMenuItem();
        mnTroGiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm bán Pizza mang về");

        jToolBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.pressedBackground"));
        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/ban-hang-icon.png"))); // NOI18N
        jButton1.setText("Bán hàng");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(10, 10));
        jToolBar1.add(jSeparator2);

        btnThemSP.setBackground(new java.awt.Color(255, 102, 0));
        btnThemSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSP.setForeground(new java.awt.Color(51, 51, 51));
        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/add-icon-24-2.png"))); // NOI18N
        btnThemSP.setText("Thêm sản phẩm");
        btnThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThemSP.setFocusable(false);
        btnThemSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThemSP);

        btnThongKe.setBackground(new java.awt.Color(255, 102, 0));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(51, 51, 51));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/thong-ke.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/password.png"))); // NOI18N
        jButton2.setText("Đổi mật khẩu");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        jToolBar1.add(jSeparator1);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/logout-icon.png"))); // NOI18N
        jButton3.setText("Đăng xuất");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton7.setBackground(new java.awt.Color(255, 102, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/exit-icon-24.png"))); // NOI18N
        jButton7.setText("Thoát");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(255, 102, 0));
        jPanel10.setLayout(new java.awt.CardLayout());

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/sanpham-pizza.png"))); // NOI18N
        jLabel2.setText("DANH SÁCH SẢN PHẨM");
        jPanel10.add(jLabel2, "card2");

        jPanel7.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7, "card2");

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHI TIẾT SẢN PHẨM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 56);
        jPanel3.add(jLabel1, gridBagConstraints);

        fmfMaSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(fmfMaSP, gridBagConstraints);

        fmfSoLuong.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(fmfSoLuong, gridBagConstraints);

        txtTenSP.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(txtTenSP, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Loại sản phẩm :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mã sản phẩm :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tên sản phẩm :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Đơn giá :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Số lượng :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(jLabel14, gridBagConstraints);

        fmfDonGia.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 14);
        jPanel3.add(fmfDonGia, gridBagConstraints);

        cbLoaiSP.setMaximumRowCount(100);
        cbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbLoaiSP.setPreferredSize(new java.awt.Dimension(215, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 8);
        jPanel3.add(cbLoaiSP, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/cart.png"))); // NOI18N
        jLabel3.setText("GIỎ HÀNG");
        jPanel6.add(jLabel3, "card2");

        jPanel8.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.CardLayout());
        jPanel8.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel13.setLayout(new java.awt.CardLayout());

        jPanel12.setLayout(new java.awt.GridBagLayout());

        txtHoTen.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(txtHoTen, gridBagConstraints);

        txtGhiChu.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(txtGhiChu, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("CHI TIẾT HÓA ĐƠN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 16, 6);
        jPanel12.add(jLabel9, gridBagConstraints);

        jLabel15.setText("MÃ NV :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel15, gridBagConstraints);

        jLabel19.setText("Họ tên NV :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel19, gridBagConstraints);

        jLabel20.setText("Mã KH :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Mã HĐ :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel21, gridBagConstraints);

        jLabel22.setText("Ngày tạo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel22, gridBagConstraints);

        jLabel23.setText("Ghi chú :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel12.add(jLabel23, gridBagConstraints);

        fmtMaNV.setColumns(15);
        fmtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fmtMaNVKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(fmtMaNV, gridBagConstraints);

        fmtMaHD.setColumns(15);
        fmtMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fmtMaHDKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(fmtMaHD, gridBagConstraints);

        fmtMaKH.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(fmtMaKH, gridBagConstraints);

        dsNgayTao.setPreferredSize(new java.awt.Dimension(165, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 25);
        jPanel12.add(dsNgayTao, gridBagConstraints);

        jPanel13.add(jPanel12, "card2");

        jPanel8.add(jPanel13, java.awt.BorderLayout.LINE_END);

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, "card2");

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.add(lblAnhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(jPanel9, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/bill-icon.png"))); // NOI18N
        jButton4.setText("Xuất hóa đơn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 6, 0);
        jPanel5.add(jButton4, gridBagConstraints);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/add-icon.png"))); // NOI18N
        jButton5.setText("Thêm vào giỏ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 6, 0);
        jPanel5.add(jButton5, gridBagConstraints);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Resources/Images/Icon/delete-icon.png"))); // NOI18N
        jButton6.setText("Xóa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 6, 0);
        jPanel5.add(jButton6, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ảnh sản phẩm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel10, gridBagConstraints);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mnTrangChu.setText("Trang chủ");
        jMenuBar1.add(mnTrangChu);

        mnSanPham.setText("Sản phẩm");

        mniThemSP.setText("Thêm sản phẩm");
        mniThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThemSPActionPerformed(evt);
            }
        });
        mnSanPham.add(mniThemSP);

        mniCNSP.setText("Cập nhật sản phẩm");
        mnSanPham.add(mniCNSP);

        mniXuatExcel.setText("Xuất file Excel");
        mniXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXuatExcelActionPerformed(evt);
            }
        });
        mnSanPham.add(mniXuatExcel);
        mnSanPham.add(jSeparator3);

        mniQLSP.setText("Quản lí sản phẩm");
        mniQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSPActionPerformed(evt);
            }
        });
        mnSanPham.add(mniQLSP);

        jMenuBar1.add(mnSanPham);

        mnHoaDon.setText("Hóa đơn");

        jMenuItem1.setText("Quản lí hóa đơn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnHoaDon.add(jMenuItem1);

        jMenuBar1.add(mnHoaDon);

        mnKhachHang.setText("Khách hàng");
        mnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhachHangActionPerformed(evt);
            }
        });

        mniThemKH.setText("Thêm khách hàng");
        mniThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThemKHActionPerformed(evt);
            }
        });
        mnKhachHang.add(mniThemKH);

        mniSuaKH.setText("Sửa khách hàng");
        mnKhachHang.add(mniSuaKH);

        mniXoaKH.setText("Xóa khách hàng");
        mnKhachHang.add(mniXoaKH);
        mnKhachHang.add(jSeparator4);

        mniQLKH.setText("Quản lí khách hàng");
        mniQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKHActionPerformed(evt);
            }
        });
        mnKhachHang.add(mniQLKH);

        jMenuBar1.add(mnKhachHang);

        mnNhanVien.setText("Nhân viên");
        mnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNhanVienActionPerformed(evt);
            }
        });

        mniThemNV.setText("Thêm nhân viên");
        mnNhanVien.add(mniThemNV);

        mniPhanQuyen.setText("Phân quyền");
        mnNhanVien.add(mniPhanQuyen);
        mnNhanVien.add(jSeparator5);

        mniQLNV.setText("Quản lí nhân viên");
        mniQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNVActionPerformed(evt);
            }
        });
        mnNhanVien.add(mniQLNV);

        jMenuBar1.add(mnNhanVien);

        mnTroGiup.setText("Trợ giúp");
        jMenuBar1.add(mnTroGiup);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    File fileAnhSP;

    private ImageIcon getAnhSP(String src) {
        src = src.trim().equals("") ? "D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham\\default.png" : src;
        //Xử lý ảnh
        BufferedImage img = null;
        File image = new File(src);

        if (!image.exists()) {
            src = "default.png";
            image = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham" + src);
        }

        try {
            img = ImageIO.read(image);
            fileAnhSP = new File(src);
        } catch (IOException e) {
            fileAnhSP = new File("D:\\NetBeansProjects\\mvc2023\\qlpizza\\src\\main\\resources\\Images\\SanPham");
        }

        if (img != null) {
            Image dimg = img.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            return new ImageIcon(dimg);
        }

        return null;
    }

    private void loadAnh(String anh) {
        lblAnhSP.setIcon(getAnhSP(anh));
    }

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tblSanPham.getSelectedRow();
        String anh = tblSanPham.getValueAt(row, 6) + "";
        if (row >= 0) {

            cbLoaiSP.setSelectedItem(tblSanPham.getValueAt(row, 2).toString());
            fmfMaSP.setText(tblSanPham.getValueAt(row, 0).toString());
            txtTenSP.setText(tblSanPham.getValueAt(row, 1).toString());
            fmfSoLuong.setText(tblSanPham.getValueAt(row, 4).toString());
            fmfDonGia.setText(tblSanPham.getValueAt(row, 3).toString());
            loadAnh("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\" + anh);
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            xuLyThemVaoGioHang();
            txtTenSP.setText("");
            fmfDonGia.setText("");
            fmfMaSP.setText("");
            fmfSoLuong.setText("");
            cbLoaiSP.setSelectedIndex(0);
            lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));

        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhachHangActionPerformed

    }//GEN-LAST:event_mnKhachHangActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        try {
            // TODO add your handling code here:
            ThongKeJFrame thongke = new ThongKeJFrame();
            thongke.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThongKeActionPerformed
    private void themSPJFrame() throws Exception {
        ThemSPJFrame themsp = new ThemSPJFrame();
        themsp.setVisible(true);
    }
    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        try {
            themSPJFrame();
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // LAY THONG TIN CTHD
        if (tblGioHang.getRowCount() == 0) {
            new MyDialog("Bạn chưa thêm sản phẩm vào giỏ!!!", MyDialog.ERROR_DIALOG);
        } else if (fmtMaNV.getText().isEmpty()) {
            new MyDialog("Bạn chưa nhập mã nhân viên thanh toán!!!", MyDialog.ERROR_DIALOG);
        } else if (fmtMaKH.getText().isEmpty() || fmtMaHD.getText().isEmpty() || txtGhiChu.getText().isEmpty() || (dsNgayTao.getDate() == null)) {
            new MyDialog("Bạn chưa nhập đầy đủ thông tin thanh toán!!!", MyDialog.ERROR_DIALOG);
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String manv = fmtMaNV.getText();
            String mahd = fmtMaHD.getText();
            Date ngaylap = dsNgayTao.getDate();
            String formattedDate = sdf.format(ngaylap);
            arrMaNV.add(fmtMaNV.getText());
            arrMaHD.add(fmtMaHD.getText());
            arrNgayLap.add(formattedDate);
            arrTenNV.add(txtHoTen.getText());
            // Xuat hd
            bHeight = Double.valueOf(itemName.size());
            //JOptionPane.showMessageDialog(rootPane, bHeight);
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(new BillPrintable(), getPageFormat(pj));
            try {
                pj.print();

            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
            new MyDialog("Xuất hóa đơn thành công!!", MyDialog.SUCCESS_DIALOG);
            insertHoaDonCSDL();
            // Reset
            resetXuatHD();
        }

    }//GEN-LAST:event_jButton4ActionPerformed
    private void insertHoaDonCSDL() {

        try {
            // Xây dựng câu lệnh SQL để insert dữ liệu
            Connection conn = Connect.getConnection();
            String sql = "INSERT INTO hoadon(MaHD, MaKH, MaNV, NgayLap, TongTien, GhiChu) VALUES (?, ?, ?, ?, ?, ?)";

            // Tạo PreparedStatement object để chứa câu lệnh SQL
            PreparedStatement pstmt = conn.prepareStatement(sql);

            // Thiết lập các tham số cho PreparedStatement object
            pstmt.setString(1, fmtMaHD.getText());
            pstmt.setString(2, fmtMaKH.getText());
            pstmt.setString(3, fmtMaNV.getText());
            pstmt.setDate(4, new java.sql.Date(dsNgayTao.getDate().getTime())); // Chuyển đổi từ java.util.Date sang java.sql.Date
            pstmt.setDouble(5, tongtatca);
            pstmt.setString(6, txtGhiChu.getText());

            // Thực thi câu lệnh SQL để insert dữ liệu
            pstmt.executeUpdate();

            // Đóng PreparedStatement object
            pstmt.close();

        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetXuatHD() {
        fmtMaHD.setText("");
        fmtMaKH.setText("");
        fmtMaNV.setText("");
        txtTenSP.setText("");
        fmfDonGia.setText("");
        fmfMaSP.setText("");
        fmfSoLuong.setText("");
        cbLoaiSP.setSelectedIndex(0);
        txtHoTen.setText("");
        txtGhiChu.setText("");
        dsNgayTao.setDate(null);
        dtmGioHang.setRowCount(0);
        fmtMaHD.setEnabled(false);
        fmtMaKH.setEnabled(false);
        dsNgayTao.setEnabled(false);
        txtGhiChu.setEnabled(false);
        lblAnhSP.setIcon(getAnhSP("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\SanPham\\default.png"));
    }

    private void xuLyXoaSPGioHang() throws Exception {
        int row = tblGioHang.getSelectedRow();
        if (row > -1) {
            int ma = Integer.parseInt(tblGioHang.getValueAt(row, 0) + "");
            int soLuong = Integer.parseInt(tblGioHang.getValueAt(row, 2) + "");
            spBUS.capNhatSoLuongSP(ma, soLuong);
            getSanPham();
            dtmGioHang.removeRow(row);
            new MyDialog("Xóa thành công!!", MyDialog.SUCCESS_DIALOG);
        }

    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn xóa không?", MyDialog.WARNING_DIALOG);
            if (dlg.OK_OPTION == dlg.getAction()) {
                xuLyXoaSPGioHang();

            } else {
                new MyDialog("Xóa thất bại!!!", MyDialog.ERROR_DIALOG);
            }

        } catch (Exception ex) {
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void fmtMaNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmtMaNVKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String pcode = fmtMaNV.getText().trim();
            if (!pcode.isEmpty()) {
                try (Connection con = Connect.getConnection(); PreparedStatement pst = con.prepareStatement("SELECT * FROM nhanvien WHERE manv = ?")) {
                    pst.setString(1, pcode);
                    try (ResultSet rs = pst.executeQuery()) {
                        if (!rs.next()) {
                            new MyDialog("Không tồn tại nhân viên có mã này!!!!", MyDialog.ERROR_DIALOG);
                            fmtMaNV.setText("");
                        } else {
                            String ho = rs.getString("ho");
                            String ten = rs.getString("ten");
                            txtHoTen.setText(ho.trim() + " " + ten.trim());
                            fmtMaHD.setEnabled(true);
                            fmtMaKH.setEnabled(true);
                            dsNgayTao.setEnabled(true);
                            txtGhiChu.setEnabled(true);
                        }
                    }
                } catch (Exception ex) {
                    new MyDialog("Mã nhân viên không hợp lệ!!!!", MyDialog.ERROR_DIALOG);
                    fmtMaNV.setText("");
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_fmtMaNVKeyPressed

    private void mniThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThemSPActionPerformed
        try {
            // TODO add your handling code here:
            themSPJFrame();
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniThemSPActionPerformed

    private void mniXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXuatExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniXuatExcelActionPerformed

    private void mnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhanVienActionPerformed
        try {
            // TODO add your handling code here:
            QLNVJFrame qlnv = new QLNVJFrame();
            qlnv.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnNhanVienActionPerformed

    private void mniThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThemKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniThemKHActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn đăng xuất không?", MyDialog.WARNING_DIALOG);
            if (dlg.OK_OPTION == dlg.getAction()) {
                LoginJDialog login = new LoginJDialog(this, rootPaneCheckingEnabled);
                this.setVisible(false);
                login.setVisible(true);
            } else {
                new MyDialog("Đăng xuất thất bại!!!", MyDialog.ERROR_DIALOG);
            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mniQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSPActionPerformed
        try {
            // TODO add your handling code here:
            QLSPJFrame qlsp = new QLSPJFrame();
            qlsp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniQLSPActionPerformed

    private void mniQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKHActionPerformed
        try {
            // TODO add your handling code here:
            QLKHJFrame qlkh = new QLKHJFrame();
            qlkh.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniQLKHActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn thoát không?", MyDialog.WARNING_DIALOG);
            if (dlg.OK_OPTION == dlg.getAction()) {
                System.exit(0);
            } else {
                new MyDialog("Thoát thất bại!!!", MyDialog.ERROR_DIALOG);
            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ChangePasswordJFrame cpw = new ChangePasswordJFrame();
        cpw.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mniQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNVActionPerformed
        try {
            // TODO add your handling code here:
            QLNVJFrame qlnv = new QLNVJFrame();
            qlnv.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniQLNVActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            getSanPham();
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // TODO add your handling code here:
            QLHDJFrame qlhd = new QLHDJFrame();
            qlhd.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void fmtMaHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmtMaHDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String pcode = fmtMaHD.getText().trim();
                if (pcode.isEmpty() || !pcode.matches("\\d+")) {
                    new MyDialog("Mã hóa đơn không hợp lệ!", MyDialog.ERROR_DIALOG);
                    fmtMaHD.setText("");
                    return;
                }

                Connection con = Connect.getConnection();
                PreparedStatement pst = con.prepareStatement("SELECT * FROM hoadon WHERE MaHD = ?");
                pst.setString(1, pcode);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    new MyDialog("Mã hóa đơn đã tồn tại!", MyDialog.ERROR_DIALOG);
                    fmtMaHD.setText("");
                }

                rs.close();
                pst.close();
                con.close();
            } catch (Exception ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_fmtMaHDKeyPressed
    private void getSanPham() throws Exception {

        DefaultTableModel dtmSanPhamBan = new DefaultTableModel();
        dtmSanPhamBan.setColumnIdentifiers(new Object[]{"Mã SP", "Tên SP", "Mã loại", "Đơn giá", "Còn lại", "Đơn vị tính", "Ảnh"});
        tblSanPham.setModel(dtmSanPhamBan);
        dtmSanPhamBan.setRowCount(0);
        ArrayList<SanPhamModel> dssp = null;
        dssp = spBUS.getListSanPham();

        for (SanPhamModel sp : dssp) {
            Vector vec = new Vector();
            vec.add(sp.getMasp());
            vec.add(sp.getTensp());
            vec.add(sp.getMaloai());
            vec.add(dcf.format(sp.getDongia()));
            vec.add(dcf.format(sp.getSoluong()));
            vec.add(sp.getDonvitinh());
            vec.add(sp.getHinhanh());
            dtmSanPhamBan.addRow(vec);
        }
    }
    DecimalFormat dcf = new DecimalFormat("###,###");

    private void xuLyThemVaoGioHang() throws Exception {

        dtmGioHang = (DefaultTableModel) tblGioHang.getModel();
        int row = tblSanPham.getSelectedRow();
        if (row < 0) {
            return;
        }
        String ma = fmfMaSP.getText();
        String ten = txtTenSP.getText();
        String donGia = fmfDonGia.getText();
        int soLuong = Integer.parseInt(fmfSoLuong.getText());
        int soLuongConLai = Integer.parseInt(tblSanPham.getValueAt(tblSanPham.getSelectedRow(), 4) + "");

        if (soLuong > soLuongConLai || soLuongConLai <= 0) {
            new MyDialog("Sản phẩm đã hết hàng", MyDialog.ERROR_DIALOG);
            return;
        }

        if (ma.trim().equalsIgnoreCase("")) {
            return;
        }
        int key = Integer.parseInt(ma);
        for (int i = 0; i < tblGioHang.getRowCount(); i++) {
            int maTbl = Integer.parseInt(tblGioHang.getValueAt(i, 0) + "");
            if (maTbl == key) {
                int soLuongAdd = Integer.parseInt(tblGioHang.getValueAt(i, 2) + "");
                soLuongAdd += soLuong;
                donGia = donGia.replace(",", "").replace(".", "");
                float donGiaSP = Float.parseFloat(donGia);

                tblGioHang.setValueAt(soLuongAdd, i, 2);
                tblGioHang.setValueAt(dcf.format(soLuong * donGiaSP), i, 4);

                // cập nhật lại số lượng trong db
                spBUS.capNhatSoLuongSP(key, -soLuong);
                spBUS.docListSanPham();
                getSanPham();
                return;
            }
        }
        Vector lst = new Vector();

        lst.add(ma);
        lst.add(ten);
        lst.add(soLuong);
        lst.add(donGia);
        donGia = donGia.replace(",", "");
        double donGiaSP = Double.parseDouble(donGia);
        double tong = (soLuong * donGiaSP);

        DecimalFormat df = new DecimalFormat("#,###");
        lst.add(df.format(tong));
//         cập nhật lại số lượng trong db
        spBUS.capNhatSoLuongSP(key, -soLuong);
        spBUS.docListSanPham();
        getSanPham();

        dtmGioHang.addRow(lst);
        new MyDialog("Thêm thành công!!", MyDialog.SUCCESS_DIALOG);

        // xu ly xuat hoa don
        itemName.add(ten);
        quantity.add(String.valueOf(soLuong));
        itemPrice.add(donGia);
        subtotal.add(String.valueOf(tong));
        tongtatca = (tongtatca + tong);

        //chuyen du lieu
//        DefaultTableModel newTableModel = new DefaultTableModel();
//        newTableModel.setDataVector(dtmGioHang.getDataVector(), dtmGioHang.getDataVector());
    }

    public PageFormat getPageFormat(PrinterJob pj) {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();
        double bodyHeight = bHeight;
        double headerHeight = 5.0;
        double footerHeight = 10.0;
        double width = cm_to_pp(16);
        double height = cm_to_pp(headerHeight + bodyHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0, 10, width, height - cm_to_pp(1));

        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);

        return pf;
    }

    public class BillPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {

            int r = itemName.size();
            ImageIcon icon = new ImageIcon("D:\\NetBeansProjects\\qlpizzamvc\\src\\Main\\Resources\\Images\\Icon\\avatar.png");
            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {

                Graphics2D g2d = (Graphics2D) graphics;
                double width = pageFormat.getImageableWidth();
                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

                //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
                try {
                    int y = 25;
                    int yShift = 10;
                    int headerRectHeight = 15;
                    // int headerRectHeighta=40;

                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 11));
                    g2d.drawImage(icon.getImage(), 150, 0, 120, 120, rootPane);
                    y += yShift + 100;
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString(" Website: www.qlpizza.com                        ", 120, y);
                    y += yShift;
                    g2d.drawString(" Số 2 Nguyễn Tri Phương                          ", 120, y);
                    y += yShift;
                    g2d.drawString(" https://www.facebook.com/P.Hungzzzzz                ", 80, y);
                    y += yShift;
                    g2d.drawString("       +976661824                             ", 120, y);
                    y += yShift;
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString(" Mã hóa đơn  : " + arrMaHD.get(0), 12, y);
                    g2d.drawString(" Mã NV tạo HD: " + arrMaNV.get(0), 200, y);
                    y += yShift;
                    g2d.drawString(" Ngày tạo    : " + arrNgayLap.get(0), 12, y);
                    g2d.drawString(" Tên NV tạo  : " + arrTenNV.get(0), 200, y);
                    y += yShift;
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += headerRectHeight;
                    g2d.drawString(" Tên sản phẩm             Số lượng   Đơn giá   Thành tiền   ", 12, y);
                    y += yShift;
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += headerRectHeight;

                    for (int s = 0; s < r; s++) {
                        DecimalFormat df = new DecimalFormat("#,###");
//                        g2d.drawString("  "+itemName.get(s) +"    " + quantity.get(s) + "    " + itemPrice.get(s)+ "    " +subtotal.get(s), 12, y);
                        g2d.drawString(" " + itemName.get(s), 12, y);
                        g2d.drawString("  " + quantity.get(s), 170, y);
                        g2d.drawString("  " + itemPrice.get(s), 245, y);
                        g2d.drawString("  " + subtotal.get(s), 315, y);
                        y += yShift;
                        g2d.drawString("", TOP_ALIGNMENT, TOP_ALIGNMENT);
                    }
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("                            Tổng hóa đơn:" + tongtatca + " VNĐ", 10, y);
                    y += yShift;
                    g2d.drawString("----------------------------------------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("                   Cảm ơn bạn, hẹn gặp lại ! !                        ", 10, y);
                    y += yShift;
                    g2d.drawString("**********************************************************************", 10, y);

                } catch (Exception e) {
                    e.printStackTrace();
                }

                result = PAGE_EXISTS;
            }
            return result;
        }
    }

    protected static double cm_to_pp(double cm) {
        return toPPI(cm * 0.393600787);
    }

    protected static double toPPI(double inch) {
        return inch * 72d;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private com.toedter.calendar.JDateChooser dsNgayTao;
    private javax.swing.JFormattedTextField fmfDonGia;
    private javax.swing.JFormattedTextField fmfMaSP;
    private javax.swing.JFormattedTextField fmfSoLuong;
    private javax.swing.JFormattedTextField fmtMaHD;
    private javax.swing.JFormattedTextField fmtMaKH;
    private javax.swing.JFormattedTextField fmtMaNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JMenu mnHoaDon;
    private javax.swing.JMenu mnKhachHang;
    private javax.swing.JMenu mnNhanVien;
    private javax.swing.JMenu mnSanPham;
    private javax.swing.JMenu mnTrangChu;
    private javax.swing.JMenu mnTroGiup;
    private javax.swing.JMenuItem mniCNSP;
    private javax.swing.JMenuItem mniPhanQuyen;
    private javax.swing.JMenuItem mniQLKH;
    private javax.swing.JMenuItem mniQLNV;
    private javax.swing.JMenuItem mniQLSP;
    private javax.swing.JMenuItem mniSuaKH;
    private javax.swing.JMenuItem mniThemKH;
    private javax.swing.JMenuItem mniThemNV;
    private javax.swing.JMenuItem mniThemSP;
    private javax.swing.JMenuItem mniXoaKH;
    private javax.swing.JMenuItem mniXuatExcel;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
